[tool.poetry]
name = "subsettools"
version = "0.1.0"
description = "Subsetting tools and utilities for ParFlow"
authors = ["George Artavanis, Amanda Triplett"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
hydrodata = {git = "ssh://git@github.com/HydroFrame-ML/hydrodata"}
numpy = ">=1.23.0"
pftools = ">=1.3.7"
xarray = "0.21.1"
rioxarray = "0.13.4"
pytz = "2020.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
